from pathlib import Path
path = Path('resources/views/presets/default/partials/header.blade.php')
text = path.read_text()
old_search_block = "            <div class=\"search position-relative d-flex align-items-center bg-white d-none d-xl-none\">\n                <div class=\"me-2 ps-2\">\n                    <i class=\"fas fa-image ps-2\"></i>\n                </div>\n                <input id=\"searchInput\" type=\"text\" autocomplete=\"off\" name=\"search\" onkeyup=\"searchList.call(this)\"\n                    class=\"form--control bg-white\" value=\"{{ isset($query) ? $query : '' }}\" placeholder=\"Search Buildings\">\n                <span class=\"pe-3\"><i class=\"fas fa-search\"></i></span>\n                <div class=\"search-result-box d-none\">\n                    <ul></ul>\n                </div>\n            </div>\n\n"
if old_search_block in text:
    text = text.replace(old_search_block, "")
# Replace nav icons container
old_icons = "            <!-- Ãcones Ã  direita (desktop) -->\n            <div class=\"d-none d-xl-flex nav-icons-right ms-3\">\n                <a href=\"{{ url('/search') }}\" class=\"nav-icon\" aria-label=\"Search\"><i class=\"fas fa-search\"></i></a>\n                <a href=\"{{ route('user.login') }}\" class=\"nav-icon\" aria-label=\"Account\"><i class=\"far fa-user\"></i></a>\n            </div>\n\n            <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\"></div>\n"
new_icons = "            <!-- Ações à direita (desktop) -->\n            <div class=\"d-none d-xl-flex nav-icons-right ms-3 align-items-center gap-3\">\n                <div class=\"navbar-search\">\n                    <button class=\"navbar-search__toggle\" id=\"navbarSearchToggle\" type=\"button\" aria-haspopup=\"true\"\n                        aria-expanded=\"false\" aria-label=\"Open search\">\n                        <i class=\"fas fa-search\"></i>\n                    </button>\n\n                    <div class=\"navbar-search__panel\" id=\"navbarSearchPanel\" aria-hidden=\"true\">\n                        <div class=\"navbar-search__card\">\n                            <div class=\"navbar-search__field\">\n                                <i class=\"fas fa-search\"></i>\n                                <input id=\"navbarSearchInput\" type=\"text\" placeholder=\"Search buildings and neighborhoods\"\n                                    autocomplete=\"off\">\n                                <button class=\"navbar-search__close\" id=\"navbarSearchClose\" type=\"button\" aria-label=\"Close search\">\n                                    <i class=\"las la-times\"></i>\n                                </button>\n                            </div>\n\n                            <div class=\"navbar-search__suggestions\">\n                                <p class=\"navbar-search__headline\">Suggested Searches</p>\n                                <ul>\n                                    <li><a href=\"javascript:void(0);\"><i class=\"las la-arrow-right\"></i> Explore 72 Park</a></li>\n                                    <li><a href=\"javascript:void(0);\"><i class=\"las la-arrow-right\"></i> Explore 72 Park</a></li>\n                                    <li><a href=\"javascript:void(0);\"><i class=\"las la-arrow-right\"></i> Explore 72 Park</a></li>\n                                    <li><a href=\"javascript:void(0);\"><i class=\"las la-arrow-right\"></i> Explore 72 Park</a></li>\n                                </ul>\n                            </div>\n                        </div>\n                    </div>\n                </div>\n                <a href=\"{{ route('user.login') }}\" class=\"nav-icon\" aria-label=\"Account\"><i class=\"far fa-user\"></i></a>\n            </div>\n\n            <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\"></div>\n"
if old_icons in text:
    text = text.replace(old_icons, new_icons)
else:
    raise SystemExit('nav icons block not found')
# Replace script block
script_start = text.find("@push('script')")
if script_start == -1:
    raise SystemExit('script block start not found')
script_end = text.find('@endpush', script_start)
if script_end == -1:
    raise SystemExit('script block end not found')
script_end += len('@endpush')
new_script = "@push('script')\n    <script>\n        document.addEventListener('DOMContentLoaded', function () {\n            const toggle = document.getElementById('navbarSearchToggle');\n            const panel = document.getElementById('navbarSearchPanel');\n            const input = document.getElementById('navbarSearchInput');\n            const closeBtn = document.getElementById('navbarSearchClose');\n\n            if (!toggle || !panel) {\n                return;\n            }\n\n            const openPanel = () => {\n                panel.classList.add('is-open');\n                panel.setAttribute('aria-hidden', 'false');\n                toggle.setAttribute('aria-expanded', 'true');\n                window.setTimeout(() => {\n                    if (input) {\n                        input.focus();\n                    }\n                }, 20);\n            };\n\n            const closePanel = () => {\n                panel.classList.remove('is-open');\n                panel.setAttribute('aria-hidden', 'true');\n                toggle.setAttribute('aria-expanded', 'false');\n                if (input) {\n                    input.value = '';\n                }\n            };\n\n            toggle.addEventListener('click', function (event) {\n                event.preventDefault();\n                event.stopPropagation();\n                event.stopImmediatePropagation();\n                if (panel.classList.contains('is-open')) {\n                    closePanel();\n                } else {\n                    openPanel();\n                }\n            });\n\n            closeBtn && closeBtn.addEventListener('click', function (event) {\n                event.preventDefault();\n                event.stopPropagation();\n                closePanel();\n            });\n\n            panel.addEventListener('click', function (event) {\n                event.stopPropagation();\n            });\n\n            document.addEventListener('click', function (event) {\n                if (!panel.classList.contains('is-open')) {\n                    return;\n                }\n\n                if (!panel.contains(event.target) && !toggle.contains(event.target)) {\n                    closePanel();\n                }\n            });\n\n            document.addEventListener('keydown', function (event) {\n                if (event.key === 'Escape') {\n                    closePanel();\n                }\n            });\n        });\n    </script>\n@endpush"
text = text[:script_start] + new_script + text[script_end:]
path.write_text(text)
